name: Run Tests
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo apt-get install -y k6

      - name: Run k6 tests and generate HTML report
        run: k6 run -o results.html ./test/first_test.js
 
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results.html

      - name: Install Newman 
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run ./test/tester-collection.json
        
  
        
     
